<!DOCTYPE html>
<html>
    <head>
        <title>Referencia a objeto no establecida como instancia de un objeto.</title>
        <meta name="viewport" content="width=device-width" />
        <style>
         body {font-family:"Verdana";font-weight:normal;font-size: .7em;color:black;} 
         p {font-family:"Verdana";font-weight:normal;color:black;margin-top: -5px}
         b {font-family:"Verdana";font-weight:bold;color:black;margin-top: -5px}
         H1 { font-family:"Verdana";font-weight:normal;font-size:18pt;color:red }
         H2 { font-family:"Verdana";font-weight:normal;font-size:14pt;color:maroon }
         pre {font-family:"Consolas","Lucida Console",Monospace;font-size:11pt;margin:0;padding:0.5em;line-height:14pt}
         .marker {font-weight: bold; color: black;text-decoration: none;}
         .version {color: gray;}
         .error {margin-bottom: 10px;}
         .expandable { text-decoration:underline; font-weight:bold; color:navy; cursor:pointer; }
         @media screen and (max-width: 639px) {
          pre { width: 440px; overflow: auto; white-space: pre-wrap; word-wrap: break-word; }
         }
         @media screen and (max-width: 479px) {
          pre { width: 280px; }
         }
        </style>
    </head>

    <body bgcolor="white">

            <span><H1>Error de servidor en la aplicación '/'.<hr width=100% size=1 color=silver></H1>

            <h2> <i>Referencia a objeto no establecida como instancia de un objeto.</i> </h2></span>

            <font face="Arial, Helvetica, Geneva, SunSans-Regular, sans-serif ">

            <b> Descripción: </b>Excepción no controlada al ejecutar la solicitud Web actual. Revise el seguimiento de la pila para obtener más información acerca del error y dónde se originó en el código.

            <br><br>

            <b> Detalles de la excepción: </b>System.NullReferenceException: Referencia a objeto no establecida como instancia de un objeto.<br><br>

            <b>Error de código fuente:</b> <br><br>

            <table width=100% bgcolor="#ffffcc">
               <tr>
                  <td>
                      <code>

Se ha generado una excepci&#243;n no controlada durante la ejecuci&#243;n de la solicitud Web actual. La informaci&#243;n sobre el origen y la ubicaci&#243;n de la excepci&#243;n pueden identificarse utilizando la excepci&#243;n del seguimiento de la pila siguiente.                      </code>

                  </td>
               </tr>
            </table>

            <br>

            <b>Seguimiento de la pila:</b> <br><br>

            <table width=100% bgcolor="#ffffcc">
               <tr>
                  <td>
                      <code><pre>

[NullReferenceException: Referencia a objeto no establecida como instancia de un objeto.]
   System.Runtime.Remoting.Proxies.RealProxy.EndInvokeHelper(Message reqMsg, Boolean bProxyCase) +428
   System.Runtime.Remoting.Proxies.RemotingProxy.Invoke(Object NotUsed, MessageData&amp; msgData) +530
   AlFramework.AsyncProcessorDelegate.EndInvoke(IAsyncResult result) +0
   AlFramework.AsyncHandler.EndProcessRequest(IAsyncResult result) in c:\GI\Proyectos\043_GI_HGF\FUENTES\043_GI_HGF\ALFramework\Web\AsyncHandler.cs:27
   System.Web.CallHandlerExecutionStep.InvokeEndHandler(IAsyncResult ar) +161
   System.Web.CallHandlerExecutionStep.OnAsyncHandlerCompletion(IAsyncResult ar) +128
</pre>                      </code>

                  </td>
               </tr>
            </table>

            <br>

            <hr width=100% size=1 color=silver>

            <b>Información de versión:</b>&nbsp;Versión de Microsoft .NET Framework:4.0.30319; Versión ASP.NET:4.8.4465.0

            </font>

    </body>
</html>
<!-- 
[NullReferenceException]: Referencia a objeto no establecida como instancia de un objeto.

Server stack trace: 
   en giControles.PdfPrintHandler.ProcessRequestCore(HttpContext context, RouteData data) en c:\GI\Proyectos\043_GI_HGF\FUENTES\043_GI_HGF\ALFramework\Web\Controles\Impresion\PdfPrint.cs:línea 731
   en AlFramework.AsyncHandler.ProcessRequest(HttpContext context) en c:\GI\Proyectos\043_GI_HGF\FUENTES\043_GI_HGF\ALFramework\Web\AsyncHandler.cs:línea 41
   en System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   en System.Runtime.Remoting.Messaging.StackBuilderSink.AsyncProcessMessage(IMessage msg, IMessageSink replySink)

Exception rethrown at [0]: 
   en System.Runtime.Remoting.Proxies.RealProxy.EndInvokeHelper(Message reqMsg, Boolean bProxyCase)
   en System.Runtime.Remoting.Proxies.RemotingProxy.Invoke(Object NotUsed, MessageData& msgData)
   en AlFramework.AsyncHandler.AsyncProcessorDelegate.EndInvoke(IAsyncResult result)
   en AlFramework.AsyncHandler.EndProcessRequest(IAsyncResult result) en c:\GI\Proyectos\043_GI_HGF\FUENTES\043_GI_HGF\ALFramework\Web\AsyncHandler.cs:línea 27
   en System.Web.HttpApplication.CallHandlerExecutionStep.InvokeEndHandler(IAsyncResult ar)
   en System.Web.HttpApplication.CallHandlerExecutionStep.OnAsyncHandlerCompletion(IAsyncResult ar)
--><!-- 
Esta página de error podría contener información confidencial porque ASP.NET está configurado para mostrar mensajes de error detallados con &lt;customErrors mode="Off"/&gt;. Considere la posibilidad de utilizar &lt;customErrors mode="On"/&gt; o &lt;customErrors mode="RemoteOnly"/&gt; en entornos de producción.-->